### ISSUE TITLE
Ability to disable loading for certain scenarios

### ISSUE THREAD

**Issue by igorlino** [AngularPlus/AngularPlus#2]
Sometimes its out of one's hand that some calls are done by 3rd party plugins.

Or perhaps, in some cases, we want another loading for some action/page.
As the shell its a higher level element in a page, nested parts of the page usually don't know about it.

Of course one could hack it, since its html anyways, but perhaps there is a cleaner way to do it.

**Comment by igorlino** [comment]
This is how I managed this:

 <div ng-show="vm.ajaxOverlay.value"
             ngplus-overlay
             ngplus-overlay-delay-in="50"
             ngplus-overlay-delay-out="700"
             ngplus-overlay-animation="dissolve-animation">
            <div class="spinner-loader"></div>
        </div>


but of course, it could be more elegant if ngplus-overlay could be called as a depedency in some controller and have a public method to call to disable/enable the overlay loading effect.

**Comment by zardaloop** [comment]
Hi @wardbell I also have similar issue. I want to hide showing overlay for the calls that my Signalr is making into server. since those calls don't have much impact on the UI, I don't see any reason to show the overlay when it is not needed. Is there any neath way of doing that?

Many thanks in advance.
